{{
  config(
    materialized='table'
  	)
}}


select distinct
upk_key2,
iff(patient_gender='M', 1, 0)::float as MALE,
age::float as age,
1::float as CONSTANT,
hf_incident_soc,
iff(hf_incident_soc in ('Outpatient Visit', 'Emergency Room'), 1, 0)::float
 as INDEX_DX_OUT,
iff(arrays_overlap((select DX_DEFIBRILLATOR from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30),1,0)::float as DX_DEFIBRILLATOR,
HF_HOSPITAL_COUNT::float as HOSP_CHF,
iff(arrays_overlap((select RX_ACE from {{ref('claims_codes_table')}}),
  ndc_prior_to_index_date_plus_30),1,0)::float as RX_ACE,
0::float as RX_ANTAGONIST,
iff(arrays_overlap((select RX_BBLOCKER from {{ref('claims_codes_table')}}),
  ndc_prior_to_index_date_plus_30),1,0)::float  as RX_BBLOCKER,
iff(arrays_overlap((select RX_DIGOXIN from {{ref('claims_codes_table')}}),
  ndc_prior_to_index_date_plus_30),1,0)::float as RX_DIGOXIN,
iff(arrays_overlap((select RX_LOOP_DIURETIC from {{ref('claims_codes_table')}}),
  ndc_prior_to_index_date_plus_30),1,0)::float as RX_LOOP_DIURETIC,
iff(arrays_overlap((select RX_NITRATES from {{ref('claims_codes_table')}}),
  ndc_prior_to_index_date_plus_30),1,0)::float as RX_NITRATES,
iff(arrays_overlap((select RX_THIAZIDE from {{ref('claims_codes_table')}}),
  ndc_prior_to_index_date_plus_30),1,0)::float as RX_THIAZIDE,
iff(arrays_overlap((select DX_AFIB from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30),1,0)::float as DX_AFIB,
iff(arrays_overlap((select DX_ANEMIA from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30),1,0)::float as DX_ANEMIA,
iff(arrays_overlap((select DX_CABG from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30) or (arrays_overlap((select CPT_CABG from {{ref('claims_codes_table')}}),
  px_prior_to_index_date_plus_30)),1,0)::float as DX_CABG,
iff(arrays_overlap((select DX_CARDIOMYOPATHY from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30),1,0)::float as DX_CARDIOMYOPATHY,
iff(arrays_overlap((select DX_COPD from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30),1,0)::float as DX_COPD,
iff(arrays_overlap((select DX_DEPRESSION from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30),1,0)::float as DX_DEPRESSION,
iff(arrays_overlap((select DX_HTN_NEPHROPATHY from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30),1,0)::float as DX_HTN_NEPHROPATHY,
iff(arrays_overlap((select DX_HYPERLIPIDEMIA from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30),1,0)::float as DX_HYPERLIPIDEMIA,
iff(arrays_overlap((select DX_HYPERTENSION from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30),1,0)::float as DX_HYPERTENSION,
iff(arrays_overlap((select DX_HYPOTENSION from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30),1,0)::float as DX_HYPOTENSION,
iff(arrays_overlap((select DX_MI from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30),1,0)::float as DX_MI,
iff(arrays_overlap((select DX_OBESITY from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30) or (arrays_overlap((select CPT_OBESITY from {{ref('claims_codes_table')}}),
  px_prior_to_index_date_plus_30)) or (arrays_overlap((select RX_OBESITY from {{ref('claims_codes_table')}}),
  ndc_prior_to_index_date_plus_30)),1,0)::float as DX_OBESITY,
iff(arrays_overlap((select DX_OTH_DYSRHYTHMIA from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30),1,0)::float as DX_OTH_DYSRHYTHMIA,
iff(arrays_overlap((select DX_PSYCHOSIS from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30),1,0)::float as DX_PSYCHOSIS,
iff(arrays_overlap((select DX_RHEUMATIC_HEART from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30),1,0)::float as DX_RHEUMATIC_HEART,
iff(arrays_overlap((select DX_SLEEP_APNEA from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30),1,0)::float as DX_SLEEP_APNEA,
iff(arrays_overlap((select DX_STABLE_ANGINA from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30),1,0)::float as DX_STABLE_ANGINA,
iff(arrays_overlap((select DX_VALVE_DISORDER from {{ref('claims_codes_table')}}),
  dx_prior_to_index_date_plus_30) or (arrays_overlap((select CPT_VALVE_DISORDER from {{ref('claims_codes_table')}}),
  px_prior_to_index_date_plus_30)),1,0)::float as DX_VALVE_DISORDER,
iff(arrays_overlap((select HF_SYSTOLIC from {{ref('claims_codes_table')}}),
  dx_on_index_date) and (not arrays_overlap((select HF_DIASTOLIC from {{ref('claims_codes_table')}}),
 dx_on_index_date)),1,0)::float as HF_SYSTOLIC,
iff(not arrays_overlap((select HF_SYSTOLIC from {{ref('claims_codes_table')}}),
  dx_on_index_date) and (arrays_overlap((select HF_DIASTOLIC from {{ref('claims_codes_table')}}),
  dx_on_index_date)),1,0)::float as HF_DIASTOLIC,
iff(arrays_overlap((select HF_SYSTOLIC from {{ref('claims_codes_table')}}),
  dx_on_index_date) and (not arrays_overlap(array_cat((select HF_DIASTOLIC from {{ref('claims_codes_table')}}),
  (select HF_SYSTOLIC from {{ref('claims_codes_table')}})),
   dx_on_index_date)),1,0)::float as HF_LEFT,
iff(arrays_overlap((select HF_UNSPECIFIED from {{ref('claims_codes_table')}}),
  dx_on_index_date) and (arrays_overlap((select HF_DIASTOLIC from {{ref('claims_codes_table')}}),
  dx_on_index_date))  and (arrays_overlap((select HF_SYSTOLIC from {{ref('claims_codes_table')}}),
  dx_on_index_date)),1,0)::float as HF_UNSPECIFIED
from {{ref('add_patient_history')}}
