  version: 2

sources:
  - name: encounters
    database: map_encounters
    schema: mx_encounters_20220105
    tables:
      - name: aa
        identifier: allowedamounts_ga
      - name: mx
        identifier: encountersmx_ls_ga
      - name: s_lines
        identifier: encountersmx_ls_ga_service_lines
      - name: visits
        identifier: visits_ls_ga
      - name: eligibility
        identifier: eligibilitystatus_ls_ga
  - name: unspecified_patients
    database: sandbox_komodo
    schema: entresto_soc 
    tables:
      - name: patients
        identifier: novartis_unspecified
  - name: patients
    database: map_patient
    schema: patient_summary_20220121
    tables:
      - name: patients_summary
        identifier: patient_summary_ls
  - name: vocabulary
    database: map_vocabulary
    schema: public
    tables:
      - name: procedure
        identifier: v_procedure